language: android
jdk: oraclejdk8
sudo: false

env:
  matrix:
    - ANDROID_API=15 #ANDROID_BUILD_TOOLS=26.0.2
    - ANDROID_API=21 #ANDROID_BUILD_TOOLS=26.0.2
    - ANDROID_API=25 #ANDROID_BUILD_TOOLS=26.0.2

android:
  components:
    - tools
    - tools # Running this twice get's the latest build tools (https://github.com/codepath/android_guides/wiki/Setting-up-Travis-CI)
    - platform-tools
    - android-${ANDROID_API}
    #- build-tools-${ANDROID_BUILD_TOOLS}
    - extra

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

script:
  - "./gradlew clean test build"

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache
